
""" Set Vim mode, not Vi
set nocompatible

""" Vundle
""" filetype off
set rtp+=~/.vim/bundle/vundle
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'altercation/vim-colors-solarized'
Bundle 'msanders/cocoa.vim'
Bundle 'pangloss/vim-javascript'
Bundle 'kien/ctrlp.vim'
Bundle 'msanders/snipmate.vim'
Bundle 'scrooloose/nerdcommenter'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/syntastic'
Bundle 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
Bundle 'Lokaltog/vim-easymotion'
Bundle 'tpope/vim-fugitive'
Bundle 'Pychimp/vim-luna'
Bundle 'Shougo/unite.vim'
Bundle 'xolox/vim-misc'
Bundle 'xolox/vim-notes'
Bundle 'cwoac/nvim'

""" Filetypes/completion
filetype plugin on
filetype indent on
set ofu=syntaxcomplete#Complete
let g:tex_flavor='latex'
let g:syntastic_python_checkers=['flake8']

""" General
set number
set backspace=eol,start,indent

set tabstop=4
set shiftwidth=4

""" Appearance
syntax on
let g:solarized_termtrans=1
set t_Co=16
set background=dark
colorscheme solarized
set laststatus=2
set ruler
set showmatch
set colorcolumn=80


inoremap jk <Esc>
inoremap kj <Esc>

let mapleader=","

let g:notes_directories = ['~/Dropbox/nvAlt']
let g:notes_suffix = '.txt'
