
""" Set Vim mode, not Vi
set nocompatible

""" Vundle
filetype off
set rtp+=~/.vim/bundle/vundle
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'altercation/vim-colors-solarized'
Bundle 'msanders/cocoa.vim'
Bundle 'wincent/command-t'
Bundle 'msanders/snipmate.vim'
Bundle 'scrooloose/nerdcommenter'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/syntastic'
Bundle 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
Bundle 'Lokaltog/vim-easymotion'
Bundle 'tpope/vim-fugitive'

""" Filetypes/completion
filetype plugin on
filetype indent on
set ofu=syntaxcomplete#Complete
let g:tex_flavor='latex'
let g:syntastic_python_checkers=['flake8']

""" General
set number
set backspace=eol,start,indent

""" Appearance
syntax on
let g:solarized_termtrans=1
set t_Co=16
set background=dark
colorscheme solarized
set laststatus=2
set ruler
set showmatch
set colorcolumn=80

imap jk <Esc>
